stages:
 - test
 - build

test:
 stage: test
 image: golang:1.21
 script:
  - go test .
 tags:
   - netology

build:
 stage: build
 image: docker:latest
 script:
  - docker build .
 tags:
   - netology
