[zabbix]
zabbix ansible_host=zabbix.ru-central1.internal

[web]
web-1 ansible_host=web-1.ru-central1.internal
web-2 ansible_host=web-2.ru-central1.internal

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/private_key
zabbix_server_ip=zabbix.ru-central1.internal
